---
- hosts: toolforge
  become: yes
  become_user: "tools.mirador"

  vars:
    base_path: /data/project/mirador

  tasks:
    - name: Clone Git repository
      git:
        repo: 'https://github.com/JeanFred/mirador-wrapper'
        dest: '{{ base_path }}/src/'

    - name: Symlink public_html
      file:
        src: '{{ base_path }}/src/'
        path: '{{ base_path }}/public_html'
        state: link
